sudo: required
 
language: bash 

services:
  - docker

before_install:
- docker pull mboehme/corebenchx

script: 
- ./run.sh corebenchx "cd /root && wget --no-check-certificate https://github.com/mboehme/corebench/archive/master.zip && unzip master.zip && cp corebench-master/corebench.tar.gz . && rm -rf corebench && tar -zxvf corebench.tar.gz"
- ./run.sh corebenchx "cd /root/corebench && ./executeTests.sh test-all core /root/corerepo"
